name: flutter_application_1
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.9.0
  intl_phone_field: ^3.2.0
  firebase_core: ^2.14.0
  firebase_auth: ^4.6.3
  otp_text_field: ^1.1.3
  http: ^1.1.0
  shared_preferences: ^2.2.0
  provider: ^6.0.5
  intl: ^0.18.1
  flutter_datetime_picker: ^1.5.1
  equatable: ^2.0.5
  dartz: ^0.10.1
  dropdown_search: ^5.0.6
  file_picker: ^5.3.3
  image_picker: ^1.0.2
  audioplayers: 
  sms_autofill: ^2.3.0
  flutter_animate: ^4.2.0+1
  google_sign_in: ^5.0.0
  font_awesome_flutter: ^10.5.0
 


dev_dependencies:
  flutter_test:
    sdk: flutter
  
 


  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
    - assets/music/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
