// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2O8IB8d_OZ_7HyEE048cNTEg1kU25p7c',
    appId: '1:690435780923:web:ce15b3c065b0a1cc0d471e',
    messagingSenderId: '690435780923',
    projectId: 'muzii-1ba76',
    authDomain: 'muzii-1ba76.firebaseapp.com',
    storageBucket: 'muzii-1ba76.appspot.com',
    measurementId: 'G-FKJVZL97J1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNOTaah78R05rAE_M7g9njSukTJfX-chQ',
    appId: '1:690435780923:android:f384317706d1ca780d471e',
    messagingSenderId: '690435780923',
    projectId: 'muzii-1ba76',
    storageBucket: 'muzii-1ba76.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpGRa9f1iM5TFL00VQqK03XEM_hRE0L_E',
    appId: '1:690435780923:ios:375246af1a4df4710d471e',
    messagingSenderId: '690435780923',
    projectId: 'muzii-1ba76',
    storageBucket: 'muzii-1ba76.appspot.com',
    androidClientId: '690435780923-gap4t3msjf1um12q07cdj9u6crh3pvfr.apps.googleusercontent.com',
    iosClientId: '690435780923-f9j8d8dcr2v337dinn45unorbnuol1tk.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpGRa9f1iM5TFL00VQqK03XEM_hRE0L_E',
    appId: '1:690435780923:ios:b824c3e2e61c5a230d471e',
    messagingSenderId: '690435780923',
    projectId: 'muzii-1ba76',
    storageBucket: 'muzii-1ba76.appspot.com',
    androidClientId: '690435780923-gap4t3msjf1um12q07cdj9u6crh3pvfr.apps.googleusercontent.com',
    iosClientId: '690435780923-1peinquvb8m64cjhhfvhq7in6rd5a0d6.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
