// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBV01B2j2A6hp42ATRdRqGUWKNGoAkiKIM',
    appId: '1:482923272018:web:23f2cc81d1d72058c30c8b',
    messagingSenderId: '482923272018',
    projectId: 'lemo-project-2143f',
    authDomain: 'lemo-project-2143f.firebaseapp.com',
    storageBucket: 'lemo-project-2143f.appspot.com',
    measurementId: 'G-DRHWHN3HF6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQ16JRLwBg91TLNss3r6HUnCxE5aZnnV8',
    appId: '1:482923272018:android:1fd403028cc75db5c30c8b',
    messagingSenderId: '482923272018',
    projectId: 'lemo-project-2143f',
    storageBucket: 'lemo-project-2143f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAf9m0LC_jvGd5DiOE1dDnhNIKd9cBk0bI',
    appId: '1:482923272018:ios:5e3d37db4c4161d1c30c8b',
    messagingSenderId: '482923272018',
    projectId: 'lemo-project-2143f',
    storageBucket: 'lemo-project-2143f.appspot.com',
    iosClientId: '482923272018-eaif26gdlcot8gnm3om9ok5uvskdlemn.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAf9m0LC_jvGd5DiOE1dDnhNIKd9cBk0bI',
    appId: '1:482923272018:ios:779816d138895e04c30c8b',
    messagingSenderId: '482923272018',
    projectId: 'lemo-project-2143f',
    storageBucket: 'lemo-project-2143f.appspot.com',
    iosClientId: '482923272018-3f36v1klr8sliarovariaq8bitj33835.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
